version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn test_kanalservis_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/backend/static
      - media_volume:/home/backend/media
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:latest
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A test_kanalservis_project worker -l info
    volumes:
      - ./test_kanalservis_project:/test_kanalservis_project
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - backend

  celery_beat:
    restart: always
    build:
      context: .
    command: celery -A test_kanalservis_project beat -l info
    volumes:
      - ./test_kanalservis_project:/test_kanalservis_project
    env_file:
      - ./.env.prod
    depends_on:
      - celery

  frontend:
    build: ./frontend

    volumes:
      - build_folder:/frontend/build
    depends_on:
      - backend
    command: serve -s build -l 8080

  nginx:
    build: ./nginx
    volumes:
      - build_folder:/var/www/frontend
    ports:
      - 80:8080
    depends_on:
      - backend
      - frontend

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  build_folder: