# Generated by Django 3.2.13 on 2022-05-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveBigIntegerField(verbose_name='Заказ №')),
                ('cost_in_rubles', models.FloatField(verbose_name='Стоимость,руб.')),
                ('cost_in_dollar', models.FloatField(verbose_name='Стоимость,дол.')),
                ('delivery_time', models.DateField(verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
